addons:
  firefox: "44.0"

language: java

jdk:
  - oraclejdk8

install:
  - rvm install 2.4.1
  - gem install octokit
  - gem install colorize

script:
  - ./gradlew clean testIntegration

after_script:
  - ruby ./scripts/publish-gh-pages.rb
  - cat liferay/liferay-ce-portal-7.0-ga3/tomcat-8.0.32/catalina.out

cache:
  directories:
    - $HOME/.m2