addons:
  firefox: "44.0"

language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew clean testIntegration

after_script:
  - mkdir reports
  - cp -R build/reports/* reports
  - git add reports
  - git commit -m "Test Reports"

